language: scala
scala:
- 2.11.12
- 2.12.4
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
jdk:
  - openjdk8
  - openjdk11
env:
  global:
    DB_URL='postgresql://localhost:5432/postgres'
services:
- postgresql
notifications:
  email: false
