version: '3'
services:
  db:
    image: postgres:latest@sha256:d61e82a1316928e732fc885b11e57de95efe018651a4ee5640b32cfe5a928d8a
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
