version: '3'
services:
  db:
    image: postgres:latest@sha256:e2e2b962e5593d80c0932397800564dc447e4381a6d4b543d19913f2a56d6fee
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
