version: '3'
services:
  db:
    image: postgres:latest@sha256:1b94cb9fe60c50a15fd4b52cc0cd6e11cc98264aa50a705161b937a2339f4d68
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
