version: '3'
services:
  db:
    image: postgres:latest@sha256:2c22778e4f1f20f4f581bdb9978948539d09360e77aac94e4a730f03d04e509a
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
