version: '3'
services:
  db:
    image: postgres:latest@sha256:cac198bf8b34aec6db64ad5771ae8918e4e16124488d8bd08533164e92d360af
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
