version: '3'
services:
  db:
    image: postgres:latest@sha256:bf74cd62c3c2bb1eaad3265417c083fc4bcb3dff66196e53c6ef6ecddc9e873a
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
