version: '3'
services:
  db:
    image: postgres:latest@sha256:065129129c847cfe876aa560dd7ca5a610c5e0bc5a4f39a36e21ccab23c173f2
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
