version: '3'
services:
  db:
    image: postgres:latest@sha256:c080bead54797fbe4e92e075cb61e957ec6dda8b8bd89ad59a91a2d3646ca677
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
