version: '3'
services:
  db:
    image: postgres:latest@sha256:b7e44e53f21728d63cd6b6d21163fbc5fccdc8f973863f95f31fdca2c8264ac5
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
