version: '3'
services:
  db:
    image: postgres:latest@sha256:e033c99282a81622b1eed36b735034e10d633a34cca3387f6142381770cfbcc8
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: MY_DB
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    volumes:
      - .:/myapp
    ports:
      - "9000:9000"
    depends_on:
      - db
