version: '3'
services:
  db:
    image: postgres:latest@sha256:35967a51fc53fd0239b98baa4adad03aa1cd13b11df377dd45253c816f0f84ec
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
