version: '3'
services:
  db:
    image: postgres:latest@sha256:47992a062f2c6dc9ec3ad7ae0298e1018dbb017b056736b9f40a1f69f39edf6e
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
