version: '3'
services:
  db:
    image: postgres:latest@sha256:33f81891e938ac26bbca81c0699dce8a1438e29f9c6767f3a6ae1a3d3b5fba98
    ports:
      - '5432:5432'
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    volumes:
      - .:/myapp
    ports:
      - "9000:9000"
    depends_on:
      - db
