version: '3'
services:
  db:
    image: postgres:latest@sha256:92703e43e363c9d1fc80f796d62a3f96ab2b46ea691a17c25b80f9be9a0f64d5
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
