version: '3'
services:
  db:
    image: postgres:latest@sha256:daf696c90ee64aebdc82be7af1e58668a1c5d73a402586d231a4693d1a1a2b0e
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
