version: '3'
services:
  db:
    image: postgres:latest@sha256:57d8817bac132c2fded9127673dd5bc7c3a97654636ce35d8f7a05cad37d37b7
    ports:
      - '5432:5432'
    tty: true
    restart: always
  web:
    build: .
    image: 9renpoto/scala
    command: sbt run
    env_file: .env
    volumes:
      - .:/myapp
    ports:
      - "8000:9000"
    depends_on:
      - db
